<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <!-- <RuntimeIdentifier>iossimulator-x86_64</RuntimeIdentifier>  -->
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>

  <!-- REQUIRED -->
  <MtouchLink>None</MtouchLink>
  <MtouchUseLlvm>false</MtouchUseLlvm>

  <!-- AOT - disable for Debug, it slows builds unnecessarily -->
  <RunAOTCompilation Condition="'$(Configuration)' == 'Release'">true</RunAOTCompilation>

  <!-- Trimming - keep full for Release only -->
  <TrimMode Condition="'$(Configuration)' == 'Release'">full</TrimMode>
  </PropertyGroup>

  <!-- <ItemGroup>
  <ProjectReference Include="../SciChart.iOS.Binding/SciChart.iOS.Binding/SciChart.iOS.Binding.csproj" />
</ItemGroup> -->

 <ItemGroup>
 <ProjectReference Include="../SciChart.iOS.Binding/SciChart.iOS.Binding.csproj" />
  <!-- <ProjectReference Include="../iOSBinding1/iOSBinding1/iOSBinding1.csproj" /> -->
</ItemGroup>
<ItemGroup>
  <BundleResource Include="Resources/marker.png" />
</ItemGroup>

</Project>